### ISSUE TITLE
mobx-react-intl

### ISSUE THREAD

**Issue by ChrisJamesC** [alexvcasillas/react-mobx-router#1]
Nice boilerplate thanks! 
You could also have a look at [mobx-react-intl](https://github.com/Sqooba/mobx-react-intl) if you prefer to use a library for internationalization. 

Disclamer: I'm the author of mobx-react-intl

**Comment by alexvcasillas** [comment]
Will take a look at it !!
Thanks for the suggestion : )
The internationalization available in this boilerplate is still a very early version of what I wanted to achieve 😅 So it could be interesting to improve the current version of this i18n or depend on some other library like yours : )

Will be in touch !

**Comment by ChrisJamesC** [comment]
Don't hesitate if I can help 😊
