### ISSUE TITLE
mobx-react-router?

### ISSUE THREAD

**Issue by corysimmons** [alexvcasillas/react-mobx-router#4]
Any reason you didn't include it?
https://github.com/alisd23/mobx-react-router

**Comment by alexvcasillas** [comment]
Why would you need mobx-react-router?

Didn't included it because I didn't want to force people use a particular routing system.

In my case I prefer react-router-dom over mobx-react-router.

**Comment by corysimmons** [comment]
Okay I see thanks

**Comment by alexvcasillas** [comment]
Thanks to you!
Maybe you could implement a branch with mobx-react-router if you would like to, I would appreciate that :)
Also another branch with react-router-dom, for example, so we can have both routing systems to choose from :)

**Comment by corysimmons** [comment]
Currently learning all this stuff. If I find a good stack I'll make a boilerplate then compare/contrast and possibly contrib?

**Comment by alexvcasillas** [comment]
Sure thing! Let me know if you need a hand with that :)
